#!/home/liqin/python3.5Env/bin/python3

from base64 import b64encode
import websocket
import _thread
import time
import json

def on_message(ws, message):

    print(message)

    notification = json.loads(message)
    ack = {'type': 'M-000', 'content': {'sequence_no': notification['sequence_no']}}

    ws.send(json.dumps(ack))

def on_error(ws, error):
    print
    error


def on_close(ws):
    print('### closed ###')


def on_open(ws):
    def run(*args):
        message = {'type': 'M-001-001', 'content': {'to': 'fbe6fb33-2bc3-4bc9-a242-3f1d0951ad6d', 'message': 'hello', 'timestamp': int(time.time())}}

        print(json.dumps(message))

        for i in range(10):
            time.sleep(1)
            ws.send(json.dumps(message))

        # ws.close()
        print('thread terminating...')

    _thread.start_new_thread(run, ())


if __name__ == "__main__":
    userAndPass = b64encode(
        b"4b7a7bf5-0b32-4361-8222-6eb3bab7e71e:08ed06a53805d141b5d7d067790169ef5eb1356664dfc4d2b8bffcf26bb39210").decode(
        "ascii")
    auth_header = 'Authorization: Basic %s' % userAndPass

    websocket.enableTrace(True)

    ws = websocket.WebSocketApp(
        "ws://121.196.226.183/v1/accounts/4049f3f2-272d-403d-9a86-7850365c51d1/online?accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NTIzOTUxMTMsImlkIjoiZjdlY2ViMTQtYTQ1NC00N2MxLWEwMjItYWM3NmQwOTQwOWJjIiwidHlwZSI6ImFwcGxpY2F0aW9uIn0.JINrOOvo2cVtht4G86jkdoRaH-RGONAZjeVt28LAG-Q&sessionID=yyy",
        header=[auth_header],
        on_message=on_message,
        on_error=on_error,
        on_close=on_close)

    ws.on_open = on_open

    ws.run_forever()
